# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# Swift package manager
# - swift build -Xswiftc \"-sdk\" -Xswiftc \"\`xcrun --sdk iphonesimulator --show-sdk-path\`\" -Xswiftc \"-target\" -Xswiftc \"x86_64-apple-ios12.1-simulator\"
script:
- set -o pipefail && xcodebuild test -workspace Example/SwiftSpreadsheet.xcworkspace -scheme SwiftSpreadsheet-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
